# name属性用来指定这个工作流的名字
name: Create release and publish NPM

on:
  # 当对分支master进行push操作的时候,触发该条工作流
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
      exists: ${{ steps.checkTag.outputs.exists }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read package.json INFO
        id: info
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo "version=${VERSION}" >> $GITHUB_ENV

      - run: echo "version - ${{ steps.info.outputs.version }}"

      - name: Check if tag exist
        id: checkTag
        uses: mukunku/tag-exists-action@v1.6.0
        if: steps.info.outputs.version != ''
        with:
          tag: 'v${{steps.info.outputs.version}}'

      - run: echo "exists - ${{ steps.checkTag.outputs.exists }}"

  publish-vite-plugin-define-pages-json:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.exists == 'false'
    environment: npm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Publish NPM
        run: pnpm publish --access public
        working-directory: packages/define-pages-json
